YotpoLtd/metorikku

CONTRIBUTING.md
https://github.com/YotpoLtd/metorikku/issues/47
=> feat(Contributing): added contributing guide

src/main/scala/com/yotpo/metorikku/output/writers/redshift/RedshiftOutputWriter.scala
fix(redshiftWriter): data type issues for default string size
=> Add_default_varchar_size_redshift_writer

examples/README.md, examples/movies.yaml
https://github.com/YotpoLtd/metorikku/issues/25
=> feat(Examples): fixed examples and examples readme

src/main/scala/com/yotpo/metorikku/output/writers/csv/CSVOutputWriter.scala, src/main/scala/com/yotpo/metorikku/output/writers/parquet/ParquetOutputWriter.scala
-feat(ParquetOutputWriter) support partitions  
-feat(CSVOutputWriter) fix default overiden behaviour
=> Metorikku writer enhancement

src/main/scala/com/yotpo/metorikku/utils/TestUtils.scala
fix(TestUtils): added missing paranthesis in Metorikku actual vs expected compare
=> hotfix_test_utils

README.md, build.sbt, src/main/scala/com/yotpo/metorikku/configuration/Output.scala, src/main/scala/com/yotpo/metorikku/configuration/outputs/Kafka.scala, src/main/scala/com/yotpo/metorikku/output/MetricOutputWriterFactory.scala, src/main/scala/com/yotpo/metorikku/output/writers/kafka/KafkaOutputWriter.scala
https://jira.yotpo.com/browse/DATA-1114
=> feat(KafkaWriter): added kafka output writer

src/main/scala/com/yotpo/metorikku/output/writers/parquet/ParquetOutputWriter.scala
add repartiton option to writer
=> BI-591_add_repartition_to_parquet_write

src/main/scala/com/yotpo/metorikku/utils/TestUtils.scala
enhance test comprehension explanations
=> BI-789_metorikku_test_suit

src/main/scala/com/yotpo/metorikku/utils/TestUtils.scala
hotfix(testUtils): resolve expected schema errors with long type and missing values
=> hotfix_test_suit_expected_schema_errors

src/main/scala/com/yotpo/metorikku/output/writers/instrumentation/InstrumentationOutputWriter.scala
=> fix(instrumentation): fixed instrumentation with key column not working as expected

README.md, build.sbt, config/sample.yaml, src/main/scala/com/yotpo/metorikku/configuration/InputCollection.scala, src/main/scala/com/yotpo/metorikku/configuration/input/Cassandra.scala, src/main/scala/com/yotpo/metorikku/input/cassandra/CassandraInput.scala
=> feat(cassandra): add support for cassandra input

.travis.yml, README.md, build.sbt, config/job_config_sample.yaml, config/metric_config_sample.yaml, e2e/elasticsearch/docker-compose.yml, e2e/elasticsearch/mocks/movies.json, e2e/elasticsearch/scripts/elasticsearch_init.sh, e2e/elasticsearch/scripts/elasticsearch_test.sh, e2e/elasticsearch/test.sh, e2e/kafka/mocks/movies.jsonl, examples/elasticsearch/movies.yaml, examples/elasticsearch/movies_metric.yaml, src/main/scala/com/yotpo/metorikku/configuration/job/Output.scala, src/main/scala/com/yotpo/metorikku/configuration/job/output/Elasticsearch.scala, src/main/scala/com/yotpo/metorikku/configuration/metric/Output.scala, src/main/scala/com/yotpo/metorikku/output/WriterFactory.scala, src/main/scala/com/yotpo/metorikku/output/writers/elasticsearch/ElasticsearchOutputWriter.scala, src/main/scala/com/yotpo/metorikku/output/writers/jdbc/JDBCQueryWriter.scala, src/main/scala/com/yotpo/metorikku/output/writers/redis/RedisOutputWriter.scala
feat(writers): add new elasticsearch writer
=> Add elasticsearch writer

README.md, build.sbt, config/job_config_sample.yaml, src/main/scala/com/yotpo/metorikku/configuration/job/input/Kafka.scala, src/main/scala/com/yotpo/metorikku/input/readers/kafka/KafkaInput.scala, src/main/scala/com/yotpo/metorikku/input/readers/kafka/deserialize/SchemaRegistryDeserializer.scala
=> feat(kafka-input): Avro serialization wth schema registry

README.md, config/job_config_sample.yaml, src/main/scala/com/yotpo/metorikku/configuration/job/input/Kafka.scala, src/main/scala/com/yotpo/metorikku/input/readers/kafka/KafkaInput.scala, src/main/scala/com/yotpo/metorikku/input/readers/kafka/deserialize/AvroToRowSchemaConverter.scala, src/main/scala/com/yotpo/metorikku/input/readers/kafka/deserialize/SchemaRegistryDeserializer.scala
=> feat(schema-registry): use avro converter 

src/main/scala/com/yotpo/metorikku/output/writers/file/HudiOutputWriter.scala
Reverts YotpoLtd/metorikku#219
=> Revert "feat(stitch_marketo_whitelist): new hudi property: whitelist"

README.md, build.sbt, examples/dq/README.md, examples/dq/movies.yaml, examples/dq/movies_metric.yaml, src/main/scala/com/yotpo/metorikku/configuration/metric/DQCheckDefinition.scala, src/main/scala/com/yotpo/metorikku/configuration/metric/Step.scala, src/main/scala/com/yotpo/metorikku/metric/StepActionFactory.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/Sql.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/DataQualityCheck.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/DataQualityCheckFactory.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/DataQualityCheckList.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/operators/isComplete.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/operators/isUnique.scala, src/test/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/IsCompleteTest.scala, src/test/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/IsUniqueTest.scala
https://jira.yotpo.com/browse/DATA-3283
=> Data 3283 add deequ

helm/spark-yotpo/templates/sparkapplication.yaml, helm/spark-yotpo/values.yaml
=> feat(k8s-values): enable Prometheus metrics

README.md, src/main/scala/com/yotpo/metorikku/code/steps/AlignTables.scala, src/main/scala/com/yotpo/metorikku/code/steps/DropColumns.scala, src/main/scala/com/yotpo/metorikku/code/steps/RemoveDuplicates.scala, src/main/scala/com/yotpo/metorikku/code/steps/SelectiveMerge.scala, src/test/scala/com/yotpo/metorikku/code/steps/test/AlignTablesTests.scala, src/test/scala/com/yotpo/metorikku/code/steps/test/CamelCaseColumnNamesTest.scala, src/test/scala/com/yotpo/metorikku/code/steps/test/LoadIfExistsTests.scala, src/test/scala/com/yotpo/metorikku/code/steps/test/RemoveDuplicatesTests.scala, src/test/scala/com/yotpo/metorikku/code/steps/test/SelectiveMergeTests.scala, src/test/scala/com/yotpo/metorikku/code/steps/test/ToAvroTests.scala
Enable removing duplicates rows from a data frame by index columns
=> feat(UDF): Add RemoveDuplicates UDF

docker/hive/init-hive.sh
This reverts commit 8431463157d747c003904ec41edfa2cdab5694eb.
=> Revert "fix(hive):disable schematool (#435)"

.travis.yml, src/main/scala/com/yotpo/metorikku/Job.scala, src/main/scala/com/yotpo/metorikku/Metorikku.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/Sql.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/DataQualityCheckList.scala, src/main/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/ValidationRunner.scala, src/main/scala/com/yotpo/metorikku/output/catalog/TableMetadata.scala, src/main/scala/com/yotpo/metorikku/output/writers/file/CatalogWriter.scala, src/main/scala/com/yotpo/metorikku/output/writers/file/FileOutputWriter.scala, src/test/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/FailedDFHandlerTest.scala, src/test/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/HasSizeTest.scala, src/test/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/HasUniquenessTest.scala, src/test/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/IsCompleteTest.scala, src/test/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/IsContainedInTest.scala, src/test/scala/com/yotpo/metorikku/metric/stepActions/dataQuality/IsUniqueTest.scala, src/test/scala/com/yotpo/metorikku/test/MetorikkuTest.scala
#425 , test to fix when using yarn
=> fix(yarn): close session on end

build.sbt
it has been deprecated and is no longer available
=> fix(sbt): remove bintray resolver
